name: CI

on:
  - push
  - pull_request

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - phpunit: 10.5.38
            php: 8.2
          - phpunit: 10.5.38
            php: 8.3
          - phpunit: 11.4.3
            php: 8.2
          - phpunit: 11.4.3
            php: 8.3
          - phpunit: 12.5.14
            php: 8.3

    steps:
      - uses: actions/checkout@v6

      - uses: php-actions/composer@v6.1.1
        with:
          php_version: ${{ matrix.php }}

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v4
        with:
          php_version: ${{ matrix.php }}
          version: ${{ matrix.phpunit }}
          test_suffix: "Test.php"
